### ISSUE TITLE
Not showing up

### ISSUE THREAD

**Issue by quizilkend** [arnowelzel/netdata-nextcloud#1]
Hey Arno,

sorr to bother you, as this is not really a bug, but a user who is not capable to get this working.

I looked for the plugin directory via
`systemctl status netdata`
and found it to be `/usr/lib/netdata/python.d/` and placed `nextcloud.chart.py` there.

I placed the nextcloud.conf config file to `/etc/netdata/python.d/`.

I got the app password from my user settings in nextcloud under security and replaced the url with the one showing up in the monitoring section of the administration panel.

But when I restart netdata, I can't see anything.

I'm on debian Buster.

Do you have an idea, what could be the problem here?

**Comment by arnowelzel** [comment]
Check if the monitoring URL actually works - open it in a browser and you should get an XML with the monitoring data.

Check the netdata logs if there is any error showing up. On my server I see the logs at `/var/log/netdata`.

Also keep in mind that it takes a moment before all plugins are showing up in the web UI of netdata since not all values are collected every second.

**Comment by quizilkend** [comment]
Hello Arno,
thanks for your reply.
The URL returns the XML data.

But I don't see anything in the netdata logs concerning the monitoring of the nextcloud instance.

**Comment by arnowelzel** [comment]
Does `grep nextcloud /var/log/netdata/*` show anything?

Is `/usr/lib/netdata/python.d/` correct? On a Ubuntu 18.04 machine the path for python plugins is `/usr/lib/exec/netdata/python.d/`.

**Comment by quizilkend** [comment]
There are plenty of logfiles(error and access ) in `/var/log/netdata/`

I guess the path is correct for debian. Because theres is no netdata under `libexec` and under `/usr/lob/netdata/python.d/` are a lot of `*.py` files.

**Comment by arnowelzel** [comment]
Maybe there is a misunderstanding: my question was, if `grep nextcloud /var/log/netdata/*` shows anything and if there are logfiles. The idea is, if the logfiles contain the word "nextcloud" to indicate an error.

Otherwise I don't know what can be wrong, sorry.

**Comment by quizilkend** [comment]
Too bad, I can't see anything in the logs connected to nextcloud.

Thank you for your help, if I find a solution i will post it here.
