### ISSUE TITLE
Fails to connect to Nextcloud's API.

### ISSUE THREAD

**Issue by Couto** [arnowelzel/netdata-nextcloud#3]
I've tried to install this collector, however when I restart the netdata service I get these logs (and a few other from the `prometheus[nextcloud_exporter_local]` which I don't think they're relevant).

```
/var/log/netdata/error.log:2020-11-27 13:58:11: python.d INFO: plugin[main] : [nextcloud] built 1 job(s) configs
/var/log/netdata/error.log:2020-11-27 13:58:15: python.d ERROR: nextcloud[local] : Url: https://example.com/ocs/v2.php/apps/serverinfo/api/v1/info?format=json. Error: HTTPSConnectionPool(host='example.com', port=443): Max retries exceeded with url: /ocs/v2.php/apps/serverinfo/api/v1/info?format=json (Caused by ReadTimeoutError("HTTPSConnectionPool(host='example.com', port=443): Read timed out. (read timeout=1)",))
/var/log/netdata/error.log:2020-11-27 13:58:15: python.d INFO: plugin[main] : nextcloud[local] : check failed
```

**Some notes**: 
1. I've replaced the original domain with `example.com` for privacy reasons.
2. The server can only be accessed by using HTTPS.
3. The original domain can only be accessed inside a local network (the internal `dig` command returns the correctly resolved IP), so I need to ask, out of ignorance, does the collector use the declared system's nameserver?
4. If I issue, from *any* machine (including from the nextcloud server) inside the local network: `curl https://example.com/ocs/v2.php/apps/serverinfo/api/v1/info?format=json`. I get the following answer: `{"ocs":{"meta":{"status":"failure","statuscode":997,"message":"Current user is not logged in"},"data":[]}}` which makes sense to me, since the request doesn't contain any credentials, however it proves that the URL is available and working.
5. Issuing a request with `curl https://user:nextcloud-app-password@example.com/ocs/v2.php/apps/serverinfo/api/v1/info?format=json` returns the correct results, which proves that the credentials are correct, although I don't think the request from the collector has reached that point yet.

I'm having some difficulties to better explain this problem, but I'm happy to answer any question you have.

**Comment by Couto** [comment]
Meanwhile, upgrading Nextcloud from v19 to v20 fixed the problem. So I guess there's a minimum requirement for this collector. 😆

**Comment by arnowelzel** [comment]
Strange - it works here with Nextcloud v19 without any issues and I started this plugin with Nextcloud v17:

![grafik](https://user-images.githubusercontent.com/6613614/100465565-d384ee80-30cf-11eb-85e2-19177af7b515.png)

**Comment by Couto** [comment]
That's incredible weird then, that was the only change I made since I reported the issue. I just upgraded NC.
Personally,  it's fine by me, it works. I just don't really know what else to say to help debug the problem.

Either way, thanks for this collector it's really useful! 👍

**Comment by olivluca** [comment]
Maybe you hit the same problem I had (or a similar one fixed in v20):
https://help.nextcloud.com/t/ocs-v2-php-apps-serverinfo-api-v1-info-takes-30-50-seconds-to-execute/83379
