### ISSUE TITLE
Timeout & other base plugin settings

### ISSUE THREAD

**Issue by tknobi** [arnowelzel/netdata-nextcloud#6]
Hi,
another problem I found with #4 was that my Nextcloud instance sometimes took a bit longer than the default timeout of 1 s and I had to increase it.

1. Should the setting [options of the base plugin](https://github.com/netdata/netdata/blob/5ddc1be576cec218b39387928325624e04e66f13/collectors/python.d.plugin/python_modules/bases/FrameworkServices/UrlService.py#L41-L56) be documented? (Or a netdata docs be linked?)
2. Shouldn't the [fixed settings](https://github.com/arnowelzel/netdata-nextcloud/blob/master/nextcloud.chart.py#L28-L30) from the nextcloud plugin be moved to the nextcloud.conf?

**Comment by arnowelzel** [comment]
Feel free to add a configuration for the plugin. I just created this for my own server were it works fine and made the source public so everyone can use it. But if you need more options - any pull request is welcome.
